/**
 * Every name `src/index.ts` exports, with what it is and what it is for.
 *
 * GENERATED by `scripts/generate-api-reference.ts` — run `pnpm docs:api`.
 * Do not edit: a summary is the first paragraph of the doc comment on the
 * declaration itself, so that is where to change one.
 *
 * Kept as data rather than as markup so the reference can be *rendered by the
 * library it documents* — the API view is a `DataTable` over this array, which
 * makes the docs a working example of the thing being documented.
 *
 * `tests/apiReference.spec.ts` regenerates this in memory and fails if it
 * differs, so the file cannot fall behind the code it describes.
 */

export type ApiKind = 'composable' | 'function' | 'component' | 'constant' | 'type'

export type ApiLayer = 'core' | 'filters' | 'sorting' | 'grouping' | 'aggregation' | 'utils' | 'primitives' | 'preset' | 'types'

export interface ApiEntry extends Record<string, unknown> {
  name: string
  layer: ApiLayer
  kind: ApiKind
  summary: string
}

export const API_LAYERS: ApiLayer[] = [
  'core',
  'filters',
  'sorting',
  'grouping',
  'aggregation',
  'utils',
  'primitives',
  'preset',
  'types',
]

export const API_KINDS: ApiKind[] = ['composable', 'function', 'component', 'constant', 'type']

export const apiReference: ApiEntry[] = [
  /* ------------------------------------------------------------------ core */
  { name: 'useTable', layer: 'core', kind: 'composable', summary: 'Wires a whole table — state, columns, drag, grouping, selection, cursor, pagination — into one `TableContext`, with no component involved.' },
  { name: 'UseTable', layer: 'core', kind: 'type', summary: 'A wired table: the `TableContext` every primitive reads, plus the few derived values a renderer needs that no primitive reaches for.' },
  { name: 'UseTableOptions', layer: 'core', kind: 'type', summary: 'Everything `useTable` accepts. See `useTable` for what is read when.' },

  { name: 'useTableState', layer: 'core', kind: 'composable', summary: "Owns the `QueryState`. Nothing here knows where rows come from — that is the data source's job — which is what lets one state object drive either." },
  { name: 'createQueryState', layer: 'core', kind: 'function', summary: 'A fresh QueryState with defaults filled in. Useful for seeding a store or a URL.' },
  { name: 'TableState', layer: 'core', kind: 'type', summary: 'What useTableState returns: refs plus the mutators that keep paging honest.' },
  { name: 'TableStateOptions', layer: 'core', kind: 'type', summary: 'pageSize, initialGroupBy, groupMode, and an external ref to mirror.' },

  { name: 'useColumns', layer: 'core', kind: 'composable', summary: 'Folds user layout state (hidden / reordered / resized / pinned) into the declared column defs, producing the list components actually render.' },
  { name: 'UseColumnsOptions', layer: 'core', kind: 'type', summary: 'Sort and filter lookups to decorate columns with, plus initial layout and storage.' },
  { name: 'UseColumnsResult', layer: 'core', kind: 'type', summary: 'all / visible columns and every layout mutator.' },
  { name: 'ColumnLayoutState', layer: 'core', kind: 'type', summary: 'The serialisable part of a layout: hidden ids, order, widths, pins.' },

  { name: 'readColumnLayout', layer: 'core', kind: 'function', summary: 'Reads a saved layout. Returns `undefined` for anything unusable — a missing, corrupt or foreign entry must not take the table down with it.' },
  { name: 'writeColumnLayout', layer: 'core', kind: 'function', summary: 'Saves the requested fields. Storage failures (quota, private mode) are ignored.' },
  { name: 'clearColumnLayout', layer: 'core', kind: 'function', summary: 'Forgets the saved layout. The in-memory one is untouched.' },
  { name: 'sanitizeColumnLayout', layer: 'core', kind: 'function', summary: 'Drops anything malformed from a stored layout rather than trusting it.' },
  { name: 'normalizeColumnStorage', layer: 'core', kind: 'function', summary: 'Resolves the storage options into a concrete key, field list and `StorageLike`.' },
  { name: 'DEFAULT_COLUMN_LAYOUT_FIELDS', layer: 'core', kind: 'constant', summary: 'The five layout fields persisted unless you narrow them.' },
  { name: 'ColumnStorageOptions', layer: 'core', kind: 'type', summary: 'Storage key, which fields to keep, and where to keep them.' },
  { name: 'ColumnLayoutField', layer: 'core', kind: 'type', summary: 'The parts of a layout that can be saved independently.' },
  { name: 'StorageLike', layer: 'core', kind: 'type', summary: 'The slice of the `Storage` DOM interface this needs. Typed structurally so a plain object works in tests and on the server.' },

  { name: 'buildHeaderRows', layer: 'core', kind: 'function', summary: 'The rows of a multi-row header: one array of cells per `<tr>`, in order.' },
  { name: 'columnBandEdges', layer: 'core', kind: 'function', summary: 'The band boundaries in a row of columns, keyed by the column each one falls to the right of.' },
  { name: 'columnGroupPath', layer: 'core', kind: 'function', summary: 'The chain of bands above a column, outermost first.' },
  { name: 'columnGroupPaths', layer: 'core', kind: 'function', summary: "Every column's band path at once, keyed by column id." },
  { name: 'foldTargetFor', layer: 'core', kind: 'function', summary: 'Which band a fold gesture on one column means, and which way — or `undefined` when the column is under no band a fold could act on.' },
  { name: 'BandEdge', layer: 'core', kind: 'type', summary: "Where a band's run ends, and how heavy the rule there should be." },

  { name: 'useColumnDnd', layer: 'core', kind: 'composable', summary: 'Pointer-driven column reordering: a drag threshold, drop sides, Escape to cancel, and keyboard moves for anyone not using a pointer.' },
  { name: 'UseColumnDnd', layer: 'core', kind: 'type', summary: 'Drag state and handlers for a header cell to bind.' },
  { name: 'UseColumnDndOptions', layer: 'core', kind: 'type', summary: 'The column order, a move callback, and canDrag / canDrop guards.' },
  { name: 'ColumnDropTarget', layer: 'core', kind: 'type', summary: 'The column a drag is currently over, and which side of it.' },
  { name: 'DropSide', layer: 'core', kind: 'type', summary: 'Which edge of the hovered column the dragged one lands on.' },

  { name: 'useRowGrouping', layer: 'core', kind: 'composable', summary: 'Turns a flat page of rows into group headers plus rows, and owns the collapse state.' },
  { name: 'UseRowGrouping', layer: 'core', kind: 'type', summary: 'displayRows, groups, overall aggregates and the collapse controls.' },
  { name: 'UseRowGroupingOptions', layer: 'core', kind: 'type', summary: 'What to group by, whole-set totals and aggregates, and the initial collapse state.' },

  { name: 'useLocalDataSource', layer: 'core', kind: 'composable', summary: 'Client-side pipeline: filter → sort → slice, each stage its own computed so paging does not redo the filter and sorting does not redo the search.' },
  { name: 'LocalDataSource', layer: 'core', kind: 'type', summary: 'A DataSource plus filteredRows, synchronous facets, and whole-set group counts.' },
  { name: 'LocalDataSourceOptions', layer: 'core', kind: 'type', summary: 'nullsLast, and debounceMs to coalesce the global search.' },

  { name: 'useServerDataSource', layer: 'core', kind: 'composable', summary: 'Server-backed rows. The component-facing surface is identical to `useLocalDataSource`, so swapping one for the other changes nothing above.' },
  { name: 'ServerDataSource', layer: 'core', kind: 'type', summary: 'A DataSource plus initialLoading, true only before anything has arrived.' },
  { name: 'ServerDataSourceOptions', layer: 'core', kind: 'type', summary: 'debounceMs, keepPreviousData, immediate, fetchFacets and onError.' },

  { name: 'useInfiniteDataSource', layer: 'core', kind: 'composable', summary: 'Server-backed rows that **accumulate** instead of being replaced: one continuous list that grows as something asks for more of it.' },
  { name: 'INFINITE_PAGE_SIZE', layer: 'core', kind: 'constant', summary: 'How many rows one request asks for, when nothing says otherwise.' },
  { name: 'InfiniteDataSource', layer: 'core', kind: 'type', summary: 'A DataSource that grows, plus what a scroll handler needs to grow it.' },
  { name: 'InfiniteDataSourceOptions', layer: 'core', kind: 'type', summary: 'pageSize, debounceMs, immediate, fetchFacets and onError.' },

  { name: 'useAsyncOptions', layer: 'core', kind: 'composable', summary: 'Options for a dropdown, fetched a portion at a time as something scrolls.' },
  { name: 'AsyncOptionsOptions', layer: 'core', kind: 'type', summary: 'debounceMs, immediate and onError.' },

  { name: 'useRowSelection', layer: 'core', kind: 'composable', summary: 'Selection that survives paging, and that can represent "everything matching the filters" without materialising an id per row.' },
  { name: 'RowClickGesture', layer: 'core', kind: 'type', summary: 'The modifiers a click carries, and nothing else about it.' },
  { name: 'UseRowSelection', layer: 'core', kind: 'type', summary: 'Selection state, predicates and mutators.' },
  { name: 'UseRowSelectionOptions', layer: 'core', kind: 'type', summary: 'Row identity, selectability, mode, and an initial selection.' },

  { name: 'useCellCursor', layer: 'core', kind: 'composable', summary: 'A focused cell you can move with the keyboard, and the highlight that follows it.' },
  { name: 'UseCellCursor', layer: 'core', kind: 'type', summary: 'Cursor position, predicates, and the movers.' },
  { name: 'UseCellCursorOptions', layer: 'core', kind: 'type', summary: 'Row identity, the columns to walk, and where to start.' },

  { name: 'useRowEditing', layer: 'core', kind: 'composable', summary: 'Inline editing: a draft per row, validated, persisted, and written back.' },
  { name: 'SAVE_FAILED_MESSAGE', layer: 'core', kind: 'constant', summary: 'Shown when a save rejected with nothing that could be turned into a message.' },
  { name: 'UseRowEditing', layer: 'core', kind: 'type', summary: 'Draft state, cell predicates, and the begin/cancel/commit mutators.' },
  { name: 'UseRowEditingOptions', layer: 'core', kind: 'type', summary: 'getRowId, mode, optimistic, validate, save, apply, mapError and the two callbacks.' },
  { name: 'EditMode', layer: 'core', kind: 'type', summary: "`'cell'` commits each field on its own; `'row'` commits a whole draft at once." },
  { name: 'RowChange', layer: 'core', kind: 'type', summary: 'What a `save` receives: the row, what changed, what it would become.' },
  { name: 'RowSaveFailure', layer: 'core', kind: 'type', summary: 'A rejected save, unpacked: a row-level message and/or per-field messages.' },
  { name: 'RowEditState', layer: 'core', kind: 'type', summary: "One row's open draft: what changed, what is wrong with it, and where it is." },

  { name: 'usePagination', layer: 'core', kind: 'composable', summary: 'Pure page arithmetic — no data, no fetching. Usable standalone for any paginated list, not just this table.' },
  { name: 'UsePagination', layer: 'core', kind: 'type', summary: 'Current page, bounds, the item list, and the navigation calls.' },
  { name: 'UsePaginationOptions', layer: 'core', kind: 'type', summary: 'siblingCount around the current page, and an onChange callback.' },
  { name: 'PageItem', layer: 'core', kind: 'type', summary: 'A page number or an ellipsis, ready to render.' },

  { name: 'useVirtualRows', layer: 'core', kind: 'composable', summary: 'A windowed range over a list of equal-height items — what to render, and how much empty space stands in for the rest.' },
  { name: 'OVERSCAN_ROWS', layer: 'core', kind: 'constant', summary: 'Rows kept rendered beyond each edge of the viewport.' },
  { name: 'UseVirtualRows', layer: 'core', kind: 'type', summary: 'The window, the space standing in for what is outside it, and the scroll offset.' },
  { name: 'UseVirtualRowsOptions', layer: 'core', kind: 'type', summary: 'rowHeight, viewportHeight, and the two knobs that turn windowing off.' },

  { name: 'provideTableContext', layer: 'core', kind: 'function', summary: 'Publishes a TableContext so primitives beneath can find it.' },
  { name: 'useTableContext', layer: 'core', kind: 'composable', summary: 'The table context, or `undefined` — which is what lets a primitive work standalone.' },
  { name: 'requireTableContext', layer: 'core', kind: 'function', summary: 'The context, or a thrown error, for the primitives that genuinely need one.' },
  { name: 'TableContextKey', layer: 'core', kind: 'constant', summary: 'The injection key, exported so you can provide a context by hand.' },
  { name: 'provideTableLabels', layer: 'core', kind: 'function', summary: 'Publishes the labels, so every primitive beneath reads the same wording.' },
  { name: 'useTableLabels', layer: 'core', kind: 'composable', summary: 'The labels a table above asked for, or the English defaults.' },
  { name: 'TableLabelsKey', layer: 'core', kind: 'constant', summary: 'The label record, published on its own key rather than as a field on `TableContext`, for the reason the theme is: a hand-built context has to satisfy that interface in full, and a caller assembling a table out of primitives should not have to hand over ~120 strings to render a pager.' },
  { name: 'TableContext', layer: 'core', kind: 'type', summary: 'Everything a primitive can reach: state, columns, source, selection, grouping, cell readers.' },
  { name: 'TableTheme', layer: 'core', kind: 'type', summary: 'A palette a table asks for outright, rather than following the OS.' },

  { name: 'DEFAULT_LABELS', layer: 'core', kind: 'constant', summary: 'The English every table renders unless it is handed something else.' },
  { name: 'mergeLabels', layer: 'core', kind: 'function', summary: '`DEFAULT_LABELS` with an override laid over it.' },
  { name: 'TableLabels', layer: 'core', kind: 'type', summary: 'The strings a table renders, overridable per table.' },

  { name: 'createTableLabels', layer: 'core', kind: 'function', summary: 'A Vue plugin that sets the wording for every table in the app at once.' },

  { name: 'defineTheme', layer: 'core', kind: 'function', summary: 'Turns a `Theme` into the custom properties that carry it, ready to bind.' },
  { name: 'Theme', layer: 'core', kind: 'type', summary: "A theme: any subset of the preset's tokens, camelCased." },
  { name: 'ThemeToken', layer: 'core', kind: 'type', summary: "One token's name, in the camelCase form a `Theme` uses." },

  { name: 'themePresets', layer: 'core', kind: 'constant', summary: 'Every palette shipped under `@brillliand/vue-table-chad/themes/`.' },
  { name: 'ThemePreset', layer: 'core', kind: 'type', summary: "One shipped palette's name — the file's basename, and the attribute value." },

  { name: 'toDelimited', layer: 'core', kind: 'function', summary: 'Serialises rows to delimited text, RFC 4180 quoted.' },
  { name: 'exportRows', layer: 'core', kind: 'function', summary: 'The whole result set as delimited text: every filtered row, in sort order.' },
  { name: 'cellText', layer: 'core', kind: 'function', summary: "A column's displayed text: its formatter, or the value stringified." },
  { name: 'DelimitedOptions', layer: 'core', kind: 'type', summary: 'How `toDelimited` writes its text.' },
  { name: 'ExportRowsOptions', layer: 'core', kind: 'type', summary: 'How `exportRows` reaches the rows to export.' },

  { name: 'editorFor', layer: 'core', kind: 'function', summary: 'Which control edits this column: its own `editor`, or one derived from `type` and from how its options are supplied.' },
  { name: 'isColumnEditable', layer: 'core', kind: 'function', summary: 'Whether this column accepts an edit to this row.' },
  { name: 'parseCellInput', layer: 'core', kind: 'function', summary: "Coerces what an editor produced into the column's own value: `column.parse`, or the coercion its `type` implies." },
  { name: 'validateCell', layer: 'core', kind: 'function', summary: "One cell's error message, or `null` when the value is acceptable." },
  { name: 'validateDraft', layer: 'core', kind: 'function', summary: 'Checks a whole draft: every changed field, then the cross-field rule.' },
  { name: 'applyCellValue', layer: 'core', kind: 'function', summary: 'Writes one value into a row, returning the next row.' },
  { name: 'applyPatch', layer: 'core', kind: 'function', summary: 'Applies a whole patch — values keyed by column id — and returns the next row.' },
  { name: 'replaceRowIn', layer: 'core', kind: 'function', summary: 'A copy of `rows` with one row swapped for its saved version, matched by id.' },
  { name: 'REQUIRED_MESSAGE', layer: 'core', kind: 'constant', summary: 'Shown when a `required` column is left blank.' },
  { name: 'CellErrors', layer: 'core', kind: 'type', summary: 'Error messages by column id — the shape both validators and a rejected save produce.' },
  { name: 'DraftValidation', layer: 'core', kind: 'type', summary: 'What a draft would produce: per-field errors, a row-level error, and the row itself.' },

  { name: 'cursorMoveFor', layer: 'core', kind: 'function', summary: 'What a key press means while a **cell** has focus, or `undefined` for a key the grid does not claim.' },
  { name: 'commitMoveFor', layer: 'core', kind: 'function', summary: 'Where the cursor goes after an Enter that commits an open editor, or `undefined` when this key press is not a commit at all.' },
  { name: 'editSeedFor', layer: 'core', kind: 'function', summary: 'The text a key press should open an editor with, or `undefined` when it starts no edit at all.' },
  { name: 'editorMoveFor', layer: 'core', kind: 'function', summary: 'Where the cursor goes when an arrow is pressed inside an **open** editor, or `undefined` when the control keeps the key for itself.' },
  { name: 'pageMoveFor', layer: 'core', kind: 'function', summary: 'Which way `Ctrl`/`Cmd` + `←`/`→` asked to turn the page — `-1` back, `1` on — or `undefined` for any other key.' },
  { name: 'scrollMoveFor', layer: 'core', kind: 'function', summary: 'Which way `Shift` + `←`/`→` asked to scroll the table sideways — `-1` left, `1` right — or `undefined` for any other key.' },
  { name: 'viewportMoveFor', layer: 'core', kind: 'function', summary: 'Which way `Ctrl`/`Cmd` + `↑`/`↓` asked to scroll the table — `-1` up, `1` down, one screenful a press — or `undefined` for any other key.' },
  { name: 'bandFoldFor', layer: 'core', kind: 'function', summary: 'Whether a key press asked to fold a header band, and which of the two ways.' },
  { name: 'nextPosition', layer: 'core', kind: 'function', summary: 'Where `move` lands, given the cells currently on screen — or `undefined` when it lands nowhere new.' },
  { name: 'nextScrollLeft', layer: 'core', kind: 'function', summary: 'Where a sideways scroll lands the scroll box, or `undefined` when it cannot move — the arithmetic behind `scrollMoveFor`, with the DOM read out of it.' },
  { name: 'nextScrollTop', layer: 'core', kind: 'function', summary: 'Where a vertical scroll lands the scroll box, or `undefined` when it cannot move — the arithmetic behind `viewportMoveFor`, with the DOM read out of it.' },
  { name: 'PAGE_MOVE_ROWS', layer: 'core', kind: 'constant', summary: 'How far PageUp and PageDown jump.' },
  { name: 'CellPosition', layer: 'core', kind: 'type', summary: 'Where the cursor is: a row and a column, by identity rather than by position.' },
  { name: 'CellCursorMark', layer: 'core', kind: 'type', summary: 'How the cursor touches one cell, as a renderer needs to know it.' },
  { name: 'CursorMove', layer: 'core', kind: 'type', summary: 'What a key press asked for, before anything knows whether it is possible.' },
  { name: 'CursorKeyGesture', layer: 'core', kind: 'type', summary: 'The parts of a key press this module reads.' },
  { name: 'BandFold', layer: 'core', kind: 'type', summary: "What a fold gesture asked for: `toggle` acts on the band over the cursor's column, `expandAll` opens every band on the table." },

  /* --------------------------------------------------------------- filters */
  { name: 'valuesFilter', layer: 'filters', kind: 'function', summary: "Excel's checkbox list: which distinct values survive." },
  { name: 'conditionsFilter', layer: 'filters', kind: 'function', summary: "Excel's operator rules, combined with and / or." },
  { name: 'isEmptyFilter', layer: 'filters', kind: 'function', summary: 'True when the filter would keep every row. Used to strip no-op filters out of `QueryState` so it stays small and URL-friendly.' },
  { name: 'isIncompleteRule', layer: 'filters', kind: 'function', summary: 'A rule that cannot narrow anything yet (operand still blank).' },
  { name: 'isUnaryOperator', layer: 'filters', kind: 'function', summary: 'Operators that take no operand: empty, notEmpty.' },
  { name: 'isBinaryOperator', layer: 'filters', kind: 'function', summary: 'Operators that take two: between.' },
  { name: 'normalizeFilter', layer: 'filters', kind: 'function', summary: 'Drops incomplete rules; returns undefined when nothing meaningful remains.' },
  { name: 'pruneFilters', layer: 'filters', kind: 'function', summary: 'Removes no-op entries so `QueryState.filters` only holds real filters.' },
  { name: 'operatorsFor', layer: 'filters', kind: 'function', summary: 'Which operators the condition builder should offer for a column type.' },
  { name: 'defaultOperator', layer: 'filters', kind: 'function', summary: 'The operator a fresh rule on this type starts with.' },
  { name: 'OPERATOR_LABELS', layer: 'filters', kind: 'constant', summary: 'Human-readable names for every operator.' },

  { name: 'matchesFilter', layer: 'filters', kind: 'function', summary: 'Does one raw cell value survive one column filter?' },
  { name: 'matchesRule', layer: 'filters', kind: 'function', summary: 'Does one value satisfy one condition rule, at this type?' },
  { name: 'matchesSearch', layer: 'filters', kind: 'function', summary: 'Case-insensitive substring match used by the global search box.' },
  { name: 'compileFilter', layer: 'filters', kind: 'function', summary: 'Pre-builds a filter into a predicate once, instead of rebuilding its value set per row.' },
  { name: 'compileSearch', layer: 'filters', kind: 'function', summary: 'The same test, with the needle lowered once instead of once per call.' },

  { name: 'computeFacets', layer: 'filters', kind: 'function', summary: "Distinct values for one column, with row counts, computed against the rows that survive every *other* column's filter." },
  { name: 'filterRows', layer: 'filters', kind: 'function', summary: 'Rows surviving every filter *except* the ones listed in `skip`.' },

  /* --------------------------------------------------------------- sorting */
  { name: 'sortRows', layer: 'sorting', kind: 'function', summary: "Stable multi-column sort, projecting each row's sort key once rather than deriving it inside the comparator." },
  { name: 'applySortRule', layer: 'sorting', kind: 'function', summary: 'Applies one sort rule to the multi-sort list.' },
  { name: 'nextDirection', layer: 'sorting', kind: 'function', summary: 'Cycles a header through asc → desc → unsorted.' },
  { name: 'comparatorFor', layer: 'sorting', kind: 'function', summary: 'The comparator a column type sorts by.' },
  { name: 'sortKeyFor', layer: 'sorting', kind: 'function', summary: 'A number a value of this type can be ordered by, or `undefined` for the types that have none.' },
  { name: 'compareText', layer: 'sorting', kind: 'function', summary: 'Text ordering, natural and case-insensitive, through the shared collator.' },
  { name: 'compareNumber', layer: 'sorting', kind: 'function', summary: 'Numeric ordering; anything uncoercible sorts last.' },
  { name: 'compareDate', layer: 'sorting', kind: 'function', summary: 'Chronological ordering, with bare YYYY-MM-DD read as local midnight.' },
  { name: 'compareBoolean', layer: 'sorting', kind: 'function', summary: 'false before true, with blanks last.' },
  { name: 'readValue', layer: 'sorting', kind: 'function', summary: "A column's value for a row: its accessor, or row[id]." },
  { name: 'SortOptions', layer: 'sorting', kind: 'type', summary: 'Sort behaviour that is not per-column — currently just blank handling.' },

  /* -------------------------------------------------------------- grouping */
  { name: 'groupedSort', layer: 'grouping', kind: 'function', summary: 'The sort a grouped table actually needs: the grouped columns first, in grouping order, then whatever the user sorted by.' },
  { name: 'groupSortRules', layer: 'grouping', kind: 'function', summary: 'Just the leading part of `groupedSort` — one rule per grouped column, in grouping order, carrying whatever direction that column was sorted by.' },
  { name: 'buildGroupTree', layer: 'grouping', kind: 'function', summary: "Builds the group tree: buckets the rows level by level and resolves each band's label, count and aggregates." },
  { name: 'flattenTree', layer: 'grouping', kind: 'function', summary: 'The cheap half: walks a built tree under the current collapse state.' },
  { name: 'flattenGroups', layer: 'grouping', kind: 'function', summary: 'Build and walk in one call, for callers doing it once.' },
  { name: 'groupValueOf', layer: 'grouping', kind: 'function', summary: 'The bucket a row falls into for one column, with every flavour of blank collapsed into one.' },
  { name: 'groupPathKey', layer: 'grouping', kind: 'function', summary: 'Stable identity for a band, built from every level above it.' },
  { name: 'groupKeys', layer: 'grouping', kind: 'function', summary: 'Every group key at every depth, ignoring collapse — what "collapse all" needs.' },
  { name: 'countGroups', layer: 'grouping', kind: 'function', summary: 'Rows per group key, at every depth. Run over a full dataset it gives group headers a count that does not shrink to whatever fits on the current page.' },
  { name: 'BLANK_GROUP_LABEL', layer: 'grouping', kind: 'constant', summary: 'What a blank group is called when the column says nothing better.' },
  { name: 'ROOT_GROUP_KEY', layer: 'grouping', kind: 'constant', summary: 'The key an empty group path produces — `groupPathKey([])` — and so the key anything covering the whole set rather than one band is filed under.' },
  { name: 'GroupingOptions', layer: 'grouping', kind: 'type', summary: 'Collapse predicate, supplied totals and aggregates, and the blank label.' },
  { name: 'GroupTreeOptions', layer: 'grouping', kind: 'type', summary: 'Everything `flattenGroups` takes except the part that folds bands shut.' },
  { name: 'GroupTree', layer: 'grouping', kind: 'type', summary: 'The grouping, before anything is folded shut.' },
  { name: 'GroupNode', layer: 'grouping', kind: 'type', summary: 'One node of the tree: a band, and the bands nested inside it.' },

  /* ----------------------------------------------------------- aggregation */
  { name: 'aggregateValue', layer: 'aggregation', kind: 'function', summary: "One column's aggregate over a set of rows, or `undefined` when the column declared none." },
  { name: 'aggregateRow', layer: 'aggregation', kind: 'function', summary: 'Every declared aggregate over one set of rows, keyed by column id.' },
  { name: 'aggregateGroups', layer: 'aggregation', kind: 'function', summary: 'Aggregates per group key, at every depth, plus the whole set under `ROOT_GROUP_KEY`.' },
  { name: 'formatAggregate', layer: 'aggregation', kind: 'function', summary: "Display text for an aggregate, through the column's `aggregateFormat` — or through `format` for a `min`/`max`." },

  /* ----------------------------------------------------------------- utils */
  { name: 'isBlank', layer: 'utils', kind: 'function', summary: 'null, undefined or the empty string — the three that must bucket together.' },
  { name: 'toNumber', layer: 'utils', kind: 'function', summary: 'A number, or undefined. Never NaN, so "skip me" is expressible.' },
  { name: 'toTime', layer: 'utils', kind: 'function', summary: 'Milliseconds since epoch, reading bare `YYYY-MM-DD` as local midnight rather than UTC. `undefined` when the value will not parse.' },
  { name: 'toIsoDate', layer: 'utils', kind: 'function', summary: '`YYYY-MM-DD` in local time — the facet key for date columns.' },
  { name: 'toBoolean', layer: 'utils', kind: 'function', summary: 'true/false from booleans, numbers, or the usual strings.' },
  { name: 'toFilterValue', layer: 'utils', kind: 'function', summary: 'Collapses a raw cell value into the JSON-safe form used inside filters and facet lists. Blanks always become `null` so they group together.' },
  { name: 'startOfDay', layer: 'utils', kind: 'function', summary: 'Local-midnight timestamp for the calendar day a value falls on.' },
  { name: 'facetKey', layer: 'utils', kind: 'function', summary: "Stable map key for a filter value (`null` and `'null'` must not collide)." },

  /* ------------------------------------------------------------ primitives */
  { name: 'TableRoot', layer: 'primitives', kind: 'component', summary: 'Wires everything together and renders nothing of its own — the slot decides the markup entirely.' },

  { name: 'TableGrid', layer: 'primitives', kind: 'component', summary: 'The `<table>` element itself, plus a `<colgroup>` driven by resolved widths so column sizing survives resizing and pinning without per-cell inline styles.' },

  { name: 'TableHeaderCell', layer: 'primitives', kind: 'component', summary: 'One `<th>`. Carries sort/pin/filter state as data-attributes and leaves all interactive bits (sort trigger, filter popover, resize handle) to slots.' },

  { name: 'TableHeaderGroupCell', layer: 'primitives', kind: 'component', summary: "A band's spanning `<th>`: its label, and the control that folds it shut." },

  { name: 'TableCell', layer: 'primitives', kind: 'component', summary: "One `<td>`, sharing the header's sticky/pin logic so columns stay aligned." },

  { name: 'TableRow', layer: 'primitives', kind: 'component', summary: 'One body row: the cells of a row, under the columns that read it.' },

  { name: 'CellEditor', layer: 'primitives', kind: 'component', summary: 'The control that edits one cell, and the keyboard contract around it.' },

  { name: 'AsyncSelect', layer: 'primitives', kind: 'component', summary: 'A dropdown whose options arrive a portion at a time, asked for as the list is scrolled.' },

  { name: 'TableGroupRow', layer: 'primitives', kind: 'component', summary: "A group header row: the expand toggle and the group's label, followed by whatever the grouped rows aggregate to, under the columns those aggregates describe." },

  { name: 'VirtualBody', layer: 'primitives', kind: 'component', summary: 'A `<tbody>` that renders only the rows the viewport can show, with empty space standing in for the rest.' },

  { name: 'SortTrigger', layer: 'primitives', kind: 'component', summary: 'The clickable header label: cycles asc → desc → unsorted, and shift-click stacks sort keys.' },

  { name: 'ColumnFilterPopover', layer: 'primitives', kind: 'component', summary: 'The funnel and its panel, teleported out of the scroll container.' },

  { name: 'ValueListFilter', layer: 'primitives', kind: 'component', summary: "Excel's checkbox list: search, tri-state \"Select All\", and a \"(Blanks)\" row." },

  { name: 'ConditionFilter', layer: 'primitives', kind: 'component', summary: "Excel's \"Text/Number/Date Filters…\" submenu: an operator-based rule builder. Offers only the operators that make sense for the column's data type." },

  { name: 'ColumnResizeHandle', layer: 'primitives', kind: 'component', summary: 'Pointer and keyboard column resizing, exposed as a `separator` role so it is reachable without a mouse.' },

  { name: 'ColumnDragGhost', layer: 'primitives', kind: 'component', summary: 'The label that follows the pointer while a column is being dragged.' },

  { name: 'ColumnVisibilityMenu', layer: 'primitives', kind: 'component', summary: 'Show/hide columns, reorder them, and pin them to either edge. Reordering is button-driven rather than drag-only so it stays keyboard-accessible.' },

  { name: 'RowGroupMenu', layer: 'primitives', kind: 'component', summary: 'Picks which columns rows are grouped by, and in which order.' },

  { name: 'ActiveFilters', layer: 'primitives', kind: 'component', summary: 'Chips summarising what is currently filtered. Without this, a filter set on a column that later got hidden or scrolled away is invisible and unexplainable.' },

  { name: 'TablePagination', layer: 'primitives', kind: 'component', summary: 'Pagination bar. Falls back to the injected table context, but every input can be passed explicitly — so it also works as a standalone pager for any list.' },

  { name: 'SelectionCheckbox', layer: 'primitives', kind: 'component', summary: 'A checkbox that tracks the indeterminate state, and stays in step when the parent refuses a change.' },

  /* ---------------------------------------------------------------- preset */
  { name: 'DataTable', layer: 'preset', kind: 'component', summary: 'The batteries-included preset: every region a named slot, and the one component that imports the default stylesheet. Deliberately NOT a god component.' },

  { name: 'downloadText', layer: 'preset', kind: 'function', summary: 'Saves text as a file the browser downloads.' },
  { name: 'TableExportPayload', layer: 'preset', kind: 'type', summary: "What `DataTable`'s `export` event carries." },

  /* ----------------------------------------------------------------- types */
  { name: 'RowId', layer: 'types', kind: 'type', summary: 'Anything a row can be keyed by.' },
  { name: 'FilterValue', layer: 'types', kind: 'type', summary: 'Values that may appear inside a serialized filter. Keep this JSON-safe.' },
  { name: 'ColumnDataType', layer: 'types', kind: 'type', summary: "How a column's values behave. Drives which comparator sorts it and which operators its filter panel offers." },
  { name: 'CellEditorKind', layer: 'types', kind: 'type', summary: 'Which control an editable column renders. Defaults from `type` — `number` and `date` to their native inputs, `boolean` to a checkbox, an `enum` that declared `options` to a select, a column that declared `asyncOptions` to the dropdown that loads them a page at a time, and everything else to a text box.' },
  { name: 'SortDirection', layer: 'types', kind: 'type', summary: "'asc' | 'desc'. Unsorted is the absence of a rule, not a third value." },
  { name: 'SortRule', layer: 'types', kind: 'type', summary: 'One sort key: a column id and a direction.' },
  { name: 'ConditionOperator', layer: 'types', kind: 'type', summary: 'Every operator across every column type.' },
  { name: 'ConditionRule', layer: 'types', kind: 'type', summary: 'An operator with up to two operands.' },
  { name: 'ValuesFilter', layer: 'types', kind: 'type', summary: "Excel's checkbox list: pick which distinct values survive." },
  { name: 'ConditionsFilter', layer: 'types', kind: 'type', summary: "Excel's \"Text/Number/Date Filters…\" submenu: operator-based rules." },
  { name: 'ColumnFilter', layer: 'types', kind: 'type', summary: 'Either kind of filter: a values checklist, or a set of condition rules.' },
  { name: 'FacetValue', layer: 'types', kind: 'type', summary: 'One distinct value plus how many rows carry it.' },
  { name: 'QueryState', layer: 'types', kind: 'type', summary: 'The serialisable description of what to show. Put it in a URL and the table is shareable.' },
  { name: 'PinSide', layer: 'types', kind: 'type', summary: "'left' | 'right' — which edge a pinned column sticks to." },
  { name: 'ColumnDef', layer: 'types', kind: 'type', summary: 'A column as you declare it: accessor, type, format, aggregate, width, pin, background.' },
  { name: 'ResolvedColumn', layer: 'types', kind: 'type', summary: 'A column after user-driven layout state (width, pin, order) is folded in.' },
  { name: 'ColumnGroupDef', layer: 'types', kind: 'type', summary: 'A band of columns above the header row: its label, its nesting, and what it folds down to.' },
  { name: 'HeaderCell', layer: 'types', kind: 'type', summary: "Either kind of header cell: a band's spanning cell, or a column's own." },
  { name: 'HeaderGroupCell', layer: 'types', kind: 'type', summary: "A band's spanning `<th>`: which columns it covers, and where it sits." },
  { name: 'HeaderColumnCell', layer: 'types', kind: 'type', summary: "One column's `<th>`, spanning down to the body from wherever its band left it." },
  { name: 'HeaderRow', layer: 'types', kind: 'type', summary: 'One `<tr>` of the header, as cells in display order.' },
  { name: 'RowGroup', layer: 'types', kind: 'type', summary: 'One bucket of rows sharing the same value on a grouped column.' },
  { name: 'DisplayRow', layer: 'types', kind: 'type', summary: 'A rendered line: either a group header or an actual row. Flattening the tree into one list is what lets the table stay a plain `<tbody>` of `<tr>`s.' },
  { name: 'GroupMode', layer: 'types', kind: 'type', summary: "Who performs the grouping: `'client'` bands the rows already loaded, `'server'` delegates it and keeps bands whole across pages." },
  { name: 'AggregateFn', layer: 'types', kind: 'type', summary: 'The aggregations a column can declare: `sum` | `avg` | `min` | `max`.' },
  { name: 'AggregateResult', layer: 'types', kind: 'type', summary: 'One computed aggregate, ready to render.' },
  { name: 'FetchParams', layer: 'types', kind: 'type', summary: 'What a server fetcher receives and must honour.' },
  { name: 'FetchResult', layer: 'types', kind: 'type', summary: 'What it must return: rows for the page, and the total across all pages.' },
  { name: 'DataSource', layer: 'types', kind: 'type', summary: 'The seam that makes local and server data interchangeable. Components consume this and never learn which implementation they were handed.' },
  { name: 'AsyncOption', layer: 'types', kind: 'type', summary: 'One choice in a dropdown: the value stored, and the text shown for it.' },
  { name: 'OptionPageRequest', layer: 'types', kind: 'type', summary: 'What a fetcher is told when the dropdown asks for the next portion.' },
  { name: 'OptionPage', layer: 'types', kind: 'type', summary: 'One portion of options, and however this endpoint says whether there are more.' },
  { name: 'AsyncOptionFetcher', layer: 'types', kind: 'type', summary: "Fetches one portion of a dropdown's options." },
  { name: 'AsyncOptionSource', layer: 'types', kind: 'type', summary: 'A growing list of options, plus what a scrolling dropdown needs to grow it. `useAsyncOptions` returns this; `ColumnDef.asyncOptions` holds one.' },
  { name: 'SelectionMode', layer: 'types', kind: 'type', summary: 'Whether one row at a time can be selected, or many.' },
  { name: 'SelectionState', layer: 'types', kind: 'type', summary: 'Explicit id list, or "everything matching the current filters minus these exclusions" — the latter is the only sane way to select 12k server rows.' },
  { name: 'HeaderCheckboxState', layer: 'types', kind: 'type', summary: "'none' | 'some' | 'all' — the tri-state header checkbox." },
]
