/**
 * Generates the docs index tables in `README.md`, `docs/getting-started.md`
 * and `docs/getting-started-js.md` from `docs/nav.ts`.
 *
 * The page list used to be maintained by hand in all three places, and they
 * drifted apart — see `DOC_PLAN.md`. `docs/nav.ts` is now the only place a
 * page's title, blurb and demo tabs are written; this script projects that
 * one array into the two shapes each file needs.
 *
 * Two variants:
 *   full   Page | What it covers | See it live — for README.md, read on
 *          GitHub, so links point at `docs/<file>`. "See it live" renders
 *          `demoTabs` as the matching tab labels from `demo/src/App.vue`.
 *   short  Page | For — for both getting-started pages, read inside the
 *          site, so links point at `<file>` directly. Each excludes itself.
 *
 * Marker comments in the three files bound what gets replaced; everything
 * outside them is untouched. Run with `pnpm docs:index`, or `--check` (which
 * `tests/docsIndex.spec.ts` drives) to fail instead of writing.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { docPages, type DocPage } from '../docs/nav.ts'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DEMO_APP = resolve(ROOT, 'demo/src/App.vue')

/**
 * Tab id -> label, parsed from the `tabs` array in `demo/src/App.vue`.
 *
 * Scoped to that one array on purpose: `App.vue` also declares a `layers`
 * array whose entries reuse the same ids (`core`, `preset`, …) with generic
 * lowercase labels, which would otherwise silently overwrite the real ones.
 * The scope ends at the `satisfies Omit<Tab, 'docs'>[]` clause that closes
 * the array literal, not a bare `]`, since the literal is now wrapped in
 * `(...).map(...)` to append `docs`.
 */
function readTabLabels(): Map<string, string> {
  const text = readFileSync(DEMO_APP, 'utf8')
  const start = text.indexOf('const tabs')
  if (start === -1) throw new Error(`${DEMO_APP}: no \`const tabs\` array found`)
  const end = text.indexOf('satisfies', start)
  if (end === -1) throw new Error(`${DEMO_APP}: no \`satisfies\` closing the \`tabs\` array`)
  const tabsSource = text.slice(start, end)

  const labels = new Map<string, string>()
  for (const match of tabsSource.matchAll(/\{\s*id:\s*'([^']+)',\s*label:\s*'([^']+)'/g)) {
    labels.set(match[1]!, match[2]!)
  }
  return labels
}

function renderFull(pages: DocPage[]): string {
  const labels = readTabLabels()
  const lines = ['| Page | What it covers | See it live |', '| --- | --- | --- |']
  for (const page of pages) {
    const live = page.demoTabs.length
      ? page.demoTabs
          .map((id) => {
            const label = labels.get(id)
            if (!label) throw new Error(`${page.file}: demoTabs names unknown tab id '${id}'`)
            return label
          })
          .join(', ')
      : '—'
    lines.push(`| [${page.title}](docs/${page.file}) | ${page.blurb} | ${live} |`)
  }
  return lines.join('\n')
}

function renderShort(pages: DocPage[], selfFile: string): string {
  const lines = ['| Page | For |', '| --- | --- |']
  for (const page of pages) {
    if (page.file === selfFile) continue
    lines.push(`| [${page.title}](${page.file}) | ${page.blurb} |`)
  }
  return lines.join('\n')
}

interface Target {
  path: string
  kind: 'full' | 'short'
  render: (pages: DocPage[]) => string
}

export const TARGETS: Target[] = [
  { path: resolve(ROOT, 'README.md'), kind: 'full', render: renderFull },
  {
    path: resolve(ROOT, 'docs/getting-started.md'),
    kind: 'short',
    render: (pages) => renderShort(pages, 'getting-started.md'),
  },
  {
    path: resolve(ROOT, 'docs/getting-started-js.md'),
    kind: 'short',
    render: (pages) => renderShort(pages, 'getting-started-js.md'),
  },
]

function markerRegex(kind: 'full' | 'short'): RegExp {
  return new RegExp(
    `(<!-- docs:index:${kind} start — generated by \`pnpm docs:index\`; edit docs/nav\\.ts -->\\n)([\\s\\S]*?)(<!-- docs:index:${kind} end -->)`,
  )
}

export function generate(path: string, kind: 'full' | 'short', render: (pages: DocPage[]) => string): string {
  const text = readFileSync(path, 'utf8')
  const regex = markerRegex(kind)
  if (!regex.test(text)) throw new Error(`${path}: no docs:index:${kind} markers found`)
  return text.replace(regex, (_match, start: string, _body: string, end: string) => `${start}${render(docPages)}\n${end}`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check')
  let drifted = false
  for (const target of TARGETS) {
    const before = readFileSync(target.path, 'utf8')
    const after = generate(target.path, target.kind, target.render)
    if (before === after) continue
    if (check) {
      drifted = true
      console.error(`${target.path} is out of date with docs/nav.ts — run \`pnpm docs:index\``)
      continue
    }
    writeFileSync(target.path, after, 'utf8')
    console.log(`${target.path} — regenerated`)
  }
  if (check && drifted) process.exit(1)
}
